/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const WaterIntakeEntry = IDL.Record({
  'amountMl' : IDL.Nat,
  'timestamp' : Time,
});
export const WeightEntry = IDL.Record({
  'weight' : IDL.Nat,
  'timestamp' : Time,
});
export const WorkoutEntry = IDL.Record({
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'timestamp' : Time,
  'exerciseName' : IDL.Text,
  'caloriesBurned' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWaterIntakeHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WaterIntakeEntry)],
      ['query'],
    ),
  'getUserWeightHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WeightEntry)],
      ['query'],
    ),
  'getUserWorkoutHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkoutEntry)],
      ['query'],
    ),
  'getWaterIntakeHistory' : IDL.Func(
      [],
      [IDL.Vec(WaterIntakeEntry)],
      ['query'],
    ),
  'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWaterIntake' : IDL.Func([IDL.Nat], [], []),
  'logWeight' : IDL.Func([IDL.Nat], [], []),
  'logWorkout' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const WaterIntakeEntry = IDL.Record({
    'amountMl' : IDL.Nat,
    'timestamp' : Time,
  });
  const WeightEntry = IDL.Record({ 'weight' : IDL.Nat, 'timestamp' : Time });
  const WorkoutEntry = IDL.Record({
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'timestamp' : Time,
    'exerciseName' : IDL.Text,
    'caloriesBurned' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWaterIntakeHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WaterIntakeEntry)],
        ['query'],
      ),
    'getUserWeightHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WeightEntry)],
        ['query'],
      ),
    'getUserWorkoutHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkoutEntry)],
        ['query'],
      ),
    'getWaterIntakeHistory' : IDL.Func(
        [],
        [IDL.Vec(WaterIntakeEntry)],
        ['query'],
      ),
    'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWaterIntake' : IDL.Func([IDL.Nat], [], []),
    'logWeight' : IDL.Func([IDL.Nat], [], []),
    'logWorkout' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };