/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaterIntakeEntry { 'amountMl' : bigint, 'timestamp' : Time }
export interface WeightEntry { 'weight' : bigint, 'timestamp' : Time }
export interface WorkoutEntry {
  'reps' : bigint,
  'sets' : bigint,
  'durationMinutes' : bigint,
  'timestamp' : Time,
  'exerciseName' : string,
  'caloriesBurned' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWaterIntakeHistory' : ActorMethod<
    [Principal],
    Array<WaterIntakeEntry>
  >,
  'getUserWeightHistory' : ActorMethod<[Principal], Array<WeightEntry>>,
  'getUserWorkoutHistory' : ActorMethod<[Principal], Array<WorkoutEntry>>,
  'getWaterIntakeHistory' : ActorMethod<[], Array<WaterIntakeEntry>>,
  'getWeightHistory' : ActorMethod<[], Array<WeightEntry>>,
  'getWorkoutHistory' : ActorMethod<[], Array<WorkoutEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWaterIntake' : ActorMethod<[bigint], undefined>,
  'logWeight' : ActorMethod<[bigint], undefined>,
  'logWorkout' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];